name: "export"
on:
  workflow_dispatch:
  push:
    paths:
      - "**.gd"
      - "**.tscn"
      - "**.import"
      - "**.tres"
      - "**.ttf"
      - ".github/workflows/export.yml"
      - "export_presets.cfg"
    branches:
      - main

jobs:
  export:
    uses: bend-n/godot-actions/.github/workflows/callable-export.yml@main
    with:
      export-name: chess
      godot-version: 3.5
      image: ghcr.io/bend-n/godot-2d:3.5
      platforms: "windows linux web android mac"
      itch-path: bendn/chess
    secrets:
      android-keystore-base64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      android-keystore-password: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      butler-api-key: ${{ secrets.BUTLER_CREDENTIALS }}
